general:
    name: 'graph_dit'
    wandb: 'disabled' 
    gpus: 1
    resume: null
    test_only: null
    # test_only: "/m2_4tdata/rzhang2/Physics-informed-Graph-DiT/graph_dit/outputs/2025-09-11/03-15-54/checkpoints/graph_dit/last.ckpt"
    sample_every_val: 2500
    samples_to_generate: 1000      
    samples_to_save: 3
    chains_to_save: 1
    log_every_steps: 50
    number_chain_steps: 8
    final_model_samples_to_generate: 10000
    final_model_samples_to_save: 20
    final_model_chains_to_save: 1
    enable_progress_bar: False
    save_model: True
model:
    type: 'discrete'
    transition: 'marginal'                  
    model: 'graph_dit'
    diffusion_steps: 1000
    diffusion_noise_schedule: 'cosine'
    guide_scale: 4
    hidden_size: 1440
    depth: 10
    num_heads: 16
    mlp_ratio: 4
    drop_condition: 0.3
    lambda_train: [1, 10]  # node and edge training weight
    #lambda_validation_head: 0.1 
    guidance_scale: 1
    ensure_connected: True
train:
    n_epochs: 10000
    batch_size: 600
    lr: 0.00005
    validation_lr: 0.00005
    clip_grad: null
    num_workers: 0
    weight_decay: 0.005
    seed: 0
    val_check_interval: null
    check_val_every_n_epoch: 1
    validity_drift_interval: 50
dataset:
    datadir: 'data/'
    task_name: null
    guidance_target: validity
    pin_memory: True
    metric_model:
        use_metric: True
        model_dir: 'data/evaluator/'
        use_registry: 'task_registry.yaml' #TODO
